// src/constants/statuses.js
module.exports = {
  USER: { PENDING_VERIFICATION: 'PENDING_VERIFICATION', ACTIVE: 'ACTIVE', SUSPENDED: 'SUSPENDED', DEACTIVATED: 'DEACTIVATED' },
  KYC: { NOT_STARTED: 'NOT_STARTED', PENDING: 'PENDING', UNDER_REVIEW: 'UNDER_REVIEW', APPROVED: 'APPROVED', REJECTED: 'REJECTED', EXPIRED: 'EXPIRED' },
  PROJECT: { DRAFT: 'DRAFT', PENDING_REVIEW: 'PENDING_REVIEW', OPEN: 'OPEN', FUNDED: 'FUNDED', CLOSED: 'CLOSED', CANCELLED: 'CANCELLED' },
  INVESTMENT: { PENDING: 'PENDING', CONFIRMED: 'CONFIRMED', ACTIVE: 'ACTIVE', MATURED: 'MATURED', WITHDRAWN: 'WITHDRAWN', CANCELLED: 'CANCELLED', DEFAULTED: 'DEFAULTED' },
  TRANSACTION: { PENDING: 'PENDING', SUCCESS: 'SUCCESS', FAILED: 'FAILED', REVERSED: 'REVERSED' },
};
